import { addDays, setHours, setMinutes } from "date-fns";
import type { EventRecord, EventSubmissionRecord } from "@/lib/types";
import { demoEvents, posterFallbacks } from "@/lib/constants";

const now = new Date();

export const sampleEvents: EventRecord[] = [
  ...demoEvents,
  {
    id: "evt-4",
    title: "Richmond Spice Trail Night Market",
    slug: "richmond-spice-trail-night-market",
    description: "Street food pop-ups, chai tastings, and live acoustic sets from South Asian performers.",
    category: "Food",
    community: "Indian / South Asian",
    city: "Richmond",
    venue_name: "Lansdowne Plaza",
    venue_address: "5300 No. 3 Rd, Richmond",
    start_time: setMinutes(setHours(addDays(now, 9), 17), 0).toISOString(),
    end_time: setMinutes(setHours(addDays(now, 9), 21), 0).toISOString(),
    price_type: "free",
    price_display: "Free entry",
    ticket_url: null,
    source_url: "https://example.com/richmond-spice-trail-night-market",
    source_name: "Community listing",
    organizer_name: "Spice Trail Society",
    poster_url: posterFallbacks[0],
    status: "approved",
    is_featured: false,
    duplicate_group_id: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: "evt-5",
    title: "Delta Temple Open House and Langar",
    slug: "delta-temple-open-house-and-langar",
    description: "A welcoming afternoon with guided temple tours, langar, and volunteer opportunities.",
    category: "Religious / Spiritual",
    community: "Indian / South Asian",
    city: "Delta",
    venue_name: "Gurdwara Community Hall",
    venue_address: "Fictional Address, Delta",
    start_time: setMinutes(setHours(addDays(now, 12), 12), 0).toISOString(),
    end_time: setMinutes(setHours(addDays(now, 12), 15), 30).toISOString(),
    price_type: "free",
    price_display: "Free",
    ticket_url: null,
    source_url: "https://example.com/delta-temple-open-house-and-langar",
    source_name: "Submitted by organizer",
    organizer_name: "Delta Sikh Outreach",
    poster_url: posterFallbacks[1],
    status: "approved",
    is_featured: false,
    duplicate_group_id: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: "evt-6",
    title: "Coquitlam Rangoli Kids Workshop",
    slug: "coquitlam-rangoli-kids-workshop",
    description: "A creative family session where children learn rangoli patterns, stories, and color techniques.",
    category: "Kids / Family",
    community: "Indian / South Asian",
    city: "Coquitlam",
    venue_name: "Evergreen Cultural Hub",
    venue_address: "Fictional Address, Coquitlam",
    start_time: setMinutes(setHours(addDays(now, 14), 10), 0).toISOString(),
    end_time: setMinutes(setHours(addDays(now, 14), 12), 0).toISOString(),
    price_type: "paid",
    price_display: "$12 per child",
    ticket_url: "https://example.com/coquitlam-rangoli-kids-workshop",
    source_url: "https://example.com/coquitlam-rangoli-kids-workshop",
    source_name: "Eventbrite",
    organizer_name: "Little Lotus Arts",
    poster_url: posterFallbacks[2],
    status: "approved",
    is_featured: false,
    duplicate_group_id: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: "evt-7",
    title: "Vancouver Carnatic Violin Circle",
    slug: "vancouver-carnatic-violin-circle",
    description: "A chamber-style recital featuring Carnatic violin, mridangam, and a short artist Q&A.",
    category: "Classical Music",
    community: "Indian / South Asian",
    city: "Vancouver",
    venue_name: "Kitsilano Arts Room",
    venue_address: "Fictional Address, Vancouver",
    start_time: setMinutes(setHours(addDays(now, 16), 19), 0).toISOString(),
    end_time: setMinutes(setHours(addDays(now, 16), 21), 15).toISOString(),
    price_type: "paid",
    price_display: "$24",
    ticket_url: "https://example.com/vancouver-carnatic-violin-circle",
    source_url: "https://example.com/vancouver-carnatic-violin-circle",
    source_name: "Indian Summer Festival",
    organizer_name: "Pacific Raga Society",
    poster_url: posterFallbacks[0],
    status: "approved",
    is_featured: false,
    duplicate_group_id: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: "evt-8",
    title: "Surrey Community Garba Night",
    slug: "surrey-community-garba-night",
    description: "An energetic garba and dandiya social with beginner-friendly instruction before the dance floor opens.",
    category: "Dance",
    community: "Indian / South Asian",
    city: "Surrey",
    venue_name: "Newton Recreation Hall",
    venue_address: "Fictional Address, Surrey",
    start_time: setMinutes(setHours(addDays(now, 18), 18), 30).toISOString(),
    end_time: setMinutes(setHours(addDays(now, 18), 22), 30).toISOString(),
    price_type: "paid",
    price_display: "$20",
    ticket_url: "https://example.com/surrey-community-garba-night",
    source_url: "https://example.com/surrey-community-garba-night",
    source_name: "Community listing",
    organizer_name: "Gujarati Cultural Circle",
    poster_url: posterFallbacks[1],
    status: "approved",
    is_featured: false,
    duplicate_group_id: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: "evt-9",
    title: "Burnaby South Indian Breakfast Club",
    slug: "burnaby-south-indian-breakfast-club",
    description: "A rotating breakfast meetup featuring dosa specials, filter coffee, and local small-business pop-ups.",
    category: "Food",
    community: "Indian / South Asian",
    city: "Burnaby",
    venue_name: "Deer Lake Social Kitchen",
    venue_address: "Fictional Address, Burnaby",
    start_time: setMinutes(setHours(addDays(now, 20), 9), 30).toISOString(),
    end_time: setMinutes(setHours(addDays(now, 20), 12), 0).toISOString(),
    price_type: "free",
    price_display: "Pay for food",
    ticket_url: null,
    source_url: "https://example.com/burnaby-south-indian-breakfast-club",
    source_name: "Submitted by organizer",
    organizer_name: "Breakfast Club Burnaby",
    poster_url: posterFallbacks[2],
    status: "approved",
    is_featured: false,
    duplicate_group_id: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: "evt-10",
    title: "Richmond Diya Decorating Circle",
    slug: "richmond-diya-decorating-circle",
    description: "A hands-on workshop for families to paint diyas, hear festival stories, and take home their creations.",
    category: "Kids / Family",
    community: "Indian / South Asian",
    city: "Richmond",
    venue_name: "Steveston Community Studio",
    venue_address: "Fictional Address, Richmond",
    start_time: setMinutes(setHours(addDays(now, 21), 13), 0).toISOString(),
    end_time: setMinutes(setHours(addDays(now, 21), 15), 0).toISOString(),
    price_type: "paid",
    price_display: "$15 per family",
    ticket_url: "https://example.com/richmond-diya-decorating-circle",
    source_url: "https://example.com/richmond-diya-decorating-circle",
    source_name: "Eventbrite",
    organizer_name: "Richmond Family Arts Guild",
    poster_url: posterFallbacks[0],
    status: "approved",
    is_featured: false,
    duplicate_group_id: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: "evt-11",
    title: "Delta Wellness and Yoga Morning",
    slug: "delta-wellness-and-yoga-morning",
    description: "A sunrise yoga class with chai, breathwork, and a short panel on community wellness habits.",
    category: "Wellness / Yoga",
    community: "Indian / South Asian",
    city: "Delta",
    venue_name: "Boundary Bay Wellness Lawn",
    venue_address: "Fictional Address, Delta",
    start_time: setMinutes(setHours(addDays(now, 24), 8), 0).toISOString(),
    end_time: setMinutes(setHours(addDays(now, 24), 10), 0).toISOString(),
    price_type: "free",
    price_display: "Free with registration",
    ticket_url: "https://example.com/delta-wellness-and-yoga-morning",
    source_url: "https://example.com/delta-wellness-and-yoga-morning",
    source_name: "Community listing",
    organizer_name: "South Asian Wellness Circle",
    poster_url: posterFallbacks[1],
    status: "approved",
    is_featured: false,
    duplicate_group_id: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
  {
    id: "evt-12",
    title: "Coquitlam South Asian Community Mixer",
    slug: "coquitlam-south-asian-community-mixer",
    description: "A casual networking evening for newcomers, entrepreneurs, volunteers, and community organizers.",
    category: "Community",
    community: "Indian / South Asian",
    city: "Coquitlam",
    venue_name: "Town Centre Commons",
    venue_address: "Fictional Address, Coquitlam",
    start_time: setMinutes(setHours(addDays(now, 27), 18), 0).toISOString(),
    end_time: setMinutes(setHours(addDays(now, 27), 20), 30).toISOString(),
    price_type: "free",
    price_display: "Free RSVP",
    ticket_url: "https://example.com/coquitlam-south-asian-community-mixer",
    source_url: "https://example.com/coquitlam-south-asian-community-mixer",
    source_name: "Submitted by organizer",
    organizer_name: "Tri-Cities South Asian Network",
    poster_url: posterFallbacks[2],
    status: "approved",
    is_featured: false,
    duplicate_group_id: null,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
  },
];

export const sampleSubmissions: EventSubmissionRecord[] = [
  {
    id: "sub-1",
    title: "Bollywood Beats on the Boardwalk",
    description: "Sunset DJ night with Bollywood and Punjabi hits.",
    category: "Bollywood / Popular Music",
    city: "Vancouver",
    venue_name: "False Creek Boardwalk Stage",
    venue_address: "Fictional Address, Vancouver",
    start_time: setMinutes(setHours(addDays(now, 8), 19), 0).toISOString(),
    end_time: setMinutes(setHours(addDays(now, 8), 22), 0).toISOString(),
    price_type: "paid",
    price_display: "$18",
    ticket_url: "https://example.com/bollywood-beats-on-the-boardwalk",
    source_url: "https://example.com/bollywood-beats-on-the-boardwalk",
    organizer_name: "City Nights Collective",
    submitter_name: "Aman Singh",
    submitter_email: "aman@example.com",
    poster_url: posterFallbacks[2],
    status: "pending",
    possible_duplicate_event_id: null,
    created_at: now.toISOString(),
  },
];
